### PR TITLE
Bump build number so cyavro rebuilds against avro 1.8.1-1

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by ericdill** [comment]
avro 1.8.1-0 has     libavro.so.22.0.0 (lib/libavro.so.22.0.0)

avro 1.8.1-1 has     libavro.so.23.0.0 (lib/libavro.so.23.0.0)

This is causing issues...

@jakirkham Can I pin by build number in the cyavro recipe here?

**Comment by jakirkham** [comment]
That is pretty rough that they changed to soname without changing the version. Do we have any idea why?

Yes you can. It goes like this `- avro 1.8.1 0`.

The third field isn't just the build number though. It is the build string. So anything that would be in the build string should be included too. That may not matter for this case.

**Comment by jakirkham** [comment]
I think I have narrowed it down. It looks like the soname changed between 1.7 and 1.8. Would restricting it to 1.7 work?

**Comment by ericdill** [comment]
yeah I think pinning to `avro 1.7.*` is the best option for now. Thanks for the help on this @jakirkham

**Comment by ericdill** [comment]
I'm also wrong about the avro 1.8.1-0 and 1.8.1-1 having different so numbers. The difference is, in fact, between 1.7.\* and 1.8.*, like you said

**Comment by ericdill** [comment]
build is failing due to a bug in conda-build.  I'll comment out that test for now

**Comment by jakirkham** [comment]
Probably this one ( https://github.com/conda/conda-build/issues/1248 ).

**Comment by ericdill** [comment]
Yup, that's the one

**Comment by ericdill** [comment]
Alright, build is passing, this is good to go.  attn @markscheevel, this will fix the libavro.so.22 vs libavro.so.23 issue

**Comment by ericdill** [comment]
Crap, I don't have write access to this repo... @mariusvniekerk !

**Comment by ericdill** [comment]
@jakirkham I work with @mariusvniekerk but he is on vacation for the next 1.5 weeks and it is unlikely that he will check email regarding this issue. This libavro shared object issue is a blocker for us right now. Could you merge this in so that we can get working cyavro/avro environments on install?

**Comment by jakirkham** [comment]
Merged. Was about to offer, but didn't want to intercede if it wasn't needed.

**Comment by ericdill** [comment]
Thanks @jakirkham !

**Comment by ericdill** [comment]
Is it appropriate to remove previous versions of cyavro from anaconda.org/conda-forge/cyavro that do not have the pinning on `avro 1.7.*`? Those cyavro packages are potentially broken if the user is not lucky enough to get `avro 1.7.*` at install time.

**Comment by jakirkham** [comment]
On it. One second...

**Comment by jakirkham** [comment]
So I didn't delete them per se, but I have placed them under a label called `broken`. That way they still exist if people are curious, but they won't be pulled in if someone is just using the `conda-forge` channel.

screen shot 2016-08-25 at 15 40 29

**Comment by ericdill** [comment]
That's a great solution. Thanks @jakirkham

**Pull request merged**
